/**
 * Milestone 0 deliverable: verify the grammar contract and emit the node-type reference.
 *
 * Usage: npm run grammar:report
 * Exits non-zero if any node kind or field required by the dialect is absent from
 * the installed grammar.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { rustNodeTypes, type NodeTypeInfo } from '../src/parser.ts';
import { REQUIRED_NODES } from '../src/dialects/bevy-0.19/grammar-contract.ts';

const require = createRequire(import.meta.url);
const tsVersion = require('tree-sitter/package.json').version as string;
const rustVersion = require('tree-sitter-rust/package.json').version as string;

export interface ContractViolation {
  node: string;
  kind: 'missing-node' | 'missing-field';
  field?: string;
}

export function verifyContract(types: NodeTypeInfo[]): ContractViolation[] {
  const byName = new Map(types.map((t) => [t.type, t]));
  const violations: ContractViolation[] = [];
  for (const [node, fields] of Object.entries(REQUIRED_NODES)) {
    const info = byName.get(node);
    if (!info) {
      violations.push({ node, kind: 'missing-node' });
      continue;
    }
    for (const field of fields) {
      if (!info.fields || !(field in info.fields)) {
        violations.push({ node, kind: 'missing-field', field });
      }
    }
  }
  return violations;
}

function digest(types: NodeTypeInfo[]): string {
  const byName = new Map(types.map((t) => [t.type, t]));
  const lines: string[] = [
    '# Rust grammar reference',
    '',
    'Generated by `npm run grammar:report` — do not edit by hand.',
    '',
    `- \`tree-sitter\` **${tsVersion}**`,
    `- \`tree-sitter-rust\` **${rustVersion}**`,
    `- node types in grammar: **${types.length}**`,
    `- node kinds required by the bevy-0.19 dialect: **${Object.keys(REQUIRED_NODES).length}**`,
    '',
    'Every node kind below is verified present at test time (`test/grammar.test.ts`),',
    'so dialect queries are written against observed structure rather than recollection.',
    '',
    '| node kind | fields used by atlas | all fields in grammar |',
    '|---|---|---|',
  ];
  for (const [node, used] of Object.entries(REQUIRED_NODES)) {
    const all = Object.keys(byName.get(node)?.fields ?? {});
    lines.push(
      `| \`${node}\` | ${used.length ? used.map((f) => `\`${f}\``).join(', ') : '—'} | ${
        all.length ? all.map((f) => `\`${f}\``).join(', ') : '—'
      } |`,
    );
  }
  lines.push(
    '',
    '## Known grammar limitations',
    '',
    'Measured against the pinned corpus at Milestone 0. Verified by `test/grammar.test.ts`.',
    '',
    '| construct | effect | files affected | handling |',
    '|---|---|---|---|',
    '| `#[cfg(...)]` in expression position | parse error; degrades to `ERROR("#")` + ' +
      '`array_expression("[cfg(...)]")` | 11 / 411 examples | pass 3 skips both artifact nodes ' +
      'when walking registration tuples |',
    '| negative const generic (`::<-1>`) | parse error in the turbofish | 1 / 411 | executor recorded, ' +
      'type argument unresolved |',
    '| one closure form in an observer argument | parse error | 1 / 411 | closure executor may be missed |',
    '',
    'Error recovery is **local**: in every affected file all `function_item` nodes still parse, and the',
    'enclosing `add_systems` call and its tuple members survive. Signature-derived access (passes 1-2)',
    'is therefore unaffected; only the mangled attribute itself must be skipped.',
    '',
  );
  return lines.join('\n') + '\n';
}

function main(): void {
  const types = rustNodeTypes();
  const violations = verifyContract(types);

  mkdirSync('reference', { recursive: true });
  writeFileSync('reference/rust-node-types.json', JSON.stringify(types, null, 2) + '\n');
  writeFileSync('reference/rust-grammar.md', digest(types));

  console.log(`tree-sitter ${tsVersion} + tree-sitter-rust ${rustVersion}`);
  console.log(`${types.length} node types -> reference/rust-node-types.json`);
  console.log(`contract: ${Object.keys(REQUIRED_NODES).length} node kinds required`);

  if (violations.length > 0) {
    console.error(`\nCONTRACT VIOLATIONS (${violations.length}):`);
    for (const v of violations) {
      console.error(
        v.kind === 'missing-node' ? `  missing node: ${v.node}` : `  missing field: ${v.node}.${v.field}`,
      );
    }
    process.exit(1);
  }
  console.log('contract: OK');
}

if (import.meta.filename === process.argv[1]) main();
